language: python
dist: trusty
python: 
  - '3.6'
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "lvh_corporation"
    token:
      secure: 97d4bd92802e51bb238349c93202a369eb85e90e

branches:
  only:
  - master
  - desenvolvimento

install:
  - pip install -r requeriments.txt

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
 # - python manage.py behave
   - sonar-scanner 

notifications:
  slack: bsi-ifserra:zHx5D7zlr2t7MxbRzI5QZ74e
