language: python
python: 
  - 3.6.5
addons:
  apt:
  sonarqube:
    organization:
    taken:
      secure:
      
branches:
  only:
    -master
    -desenvolvimento
    
notifications:
  slack: bsi-ifserra:zHx5D7zlr2t7MxbRzI5QZ74e  
    
install:
  -pip install -r requiriments.txt
  
script:
  -python manage.py behave
  -cd..
  -cd..
  -sonar-scanner
  
deploy:  
