language: python
python: 
  - 3.6.5
jdk:
  - oraclejdk8
  
addons:
  apt:  
    packages:
      - oracle-java8-installer  
  sonarqube:
    organization: "lvh_corporation"
    token:
      secure:"$SENHA_SONNAR"

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
      
branches:
  only:
    -master
    -desenvolvimento
    
notifications:
  slack: bsi-ifserra:zHx5D7zlr2t7MxbRzI5QZ74e  
    
install:
  -pip install -r requiriments.txt
  
script:
  -python manage.py behave  
  -sonar-scanner
