language: python
dist: trusty
python: 
    - '3.6'
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-installer
    sonarcloud:
        organization: "lvh_corporation"
        token:
            secure: $SONNAR_SENHA

branches:
    only:
    - master
    - desenvolvimento

before_install:
    - sudo apt-get install -y jq
  
install:
    - pip install -r requirements.txt


before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
    - python manage.py behave
    - sonar-scanner > sonar.txt
    - sh breakingbuildsonar.sh sonar.txt $SONNAR_SENHA https://sonarcloud.io
    - rm sonar.txt

notifications:
    slack: bsi-ifserra:zHx5D7zlr2t7MxbRzI5QZ74e
