language: python
python: 
  - 3.6.5
addons:
  apt:
  sonarqube:
    organization: "lvh_corporation"
    token:
      secure:"$SENHA_SONNAR"
      
branches:
  only:
    -master
    -desenvolvimento
    
notifications:
  slack: bsi-ifserra:zHx5D7zlr2t7MxbRzI5QZ74e  
    
install:
  -pip install -r requiriments.txt
  
script:
  -python manage.py behave  
  -sonar-scanner
