# Generated by Django 2.0.5 on 2018-05-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('semestreEntrada', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCurso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEstado', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMateria', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioAtendimento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField(verbose_name='date published')),
                ('horasMinistradas', models.IntegerField(default=0)),
                ('linkListaPresenca', models.CharField(max_length=200)),
                ('qtdAlunosPresentes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='atendimentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.RegistroAtendimento'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.EstadoMonitor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Curso'),
        ),
    ]
