# Generated by Django 2.0.5 on 2018-06-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestreEntrada', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPedeMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('periodo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCurso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEstado', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMateria', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioAtendimento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estaNaComissao', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='date published')),
                ('horasMinistradas', models.IntegerField(default=0)),
                ('linkListaPresenca', models.CharField(max_length=200)),
                ('qtdAlunosPresentes', models.IntegerField(default=0)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VagaMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdInscritos', models.IntegerField(default=0)),
                ('semestreEntrada', models.IntegerField()),
                ('descricaoResultado', models.TextField()),
                ('candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Aluno')),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='atendimentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.RegistroAtendimento'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.EstadoMonitor'),
        ),
        migrations.AddField(
            model_name='alunopedemonitor',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Materia'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsistema.Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
