# Generated by Django 2.0.5 on 2018-06-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
    ]
