# Generated by Django 2.0.5 on 2018-06-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsistema', '0003_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunopedemonitor',
            name='periodo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='responsavel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='subsistema.Aluno'),
            preserve_default=False,
        ),
    ]
